services:
  db:
    image: gvenzl/oracle-free:latest
    container_name: backend-oracle-1
    environment:
      - ORACLE_PASSWORD=mavunoadmin
      - APP_USER=mavuno
      - APP_PASSWORD=mavuno
    ports:
      - "1521:1521"
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: