import os
import oracledb

class MigrationRunner:
    def __init__(self, db_connection):
        self.db = db_connection
        self.cursor = self.db.cursor()
        self._ensure_history_table()

    def _ensure_history_table(self):
        """Create a table to track applied migrations if it doesn't exist."""
        try:
            self.cursor.execute(
                "SELECT count(*) FROM user_tables WHERE table_name = 'MIGRATION_HISTORY'"
            )
            if self.cursor.fetchone()[0] == 0:
                self.cursor.execute("""
                    CREATE TABLE migration_history (
                        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        migration_name VARCHAR2(255) NOT NULL UNIQUE,
                        applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                    )
                """)
                self.db.commit()
        except oracledb.Error as e:
            print(f"Error setting up migration history: {e}")
            raise

    def _get_applied_migrations(self):
        """Fetch a set of already applied migration filenames."""
        self.cursor.execute("SELECT migration_name FROM migration_history")
        return {row[0] for row in self.cursor.fetchall()}

    def run_migration(self, migration_file):
        """Run a single migration file"""
        filename = os.path.basename(migration_file)
        print(f"Running migration: {filename}...")
        
        with open(migration_file, 'r') as f:
            sql_script = f.read()

        # Oracle's execute() does not accept trailing semicolons for single statements.
        # We split by ';' to handle multiple statements in a single .sql file.
        statements = [s.strip() for s in sql_script.split(';') if s.strip()]
        
        try:
            for statement in statements:
                self.cursor.execute(statement)
            
            # Record the successful migration
            self.cursor.execute(
                "INSERT INTO migration_history (migration_name) VALUES (:name)",
                [filename]
            )
            self.db.commit()
            print(f"Successfully applied {filename}")
            
        except oracledb.Error as e:
            self.db.rollback()
            print(f"Failed to apply {filename}: {e}")
            raise

    def run_all_migrations(self, migrations_dir):
        """Run all pending migrations in sequential order"""
        print("Checking for pending migrations...")
        applied_migrations = self._get_applied_migrations()
        
        # Grab all .sql files and sort them to guarantee 001 runs before 002
        files = sorted([f for f in os.listdir(migrations_dir) if f.endswith('.sql')])
        pending_files = [f for f in files if f not in applied_migrations]
        
        if not pending_files:
            print("Database is up to date. No pending migrations found.")
            return

        for file in pending_files:
            file_path = os.path.join(migrations_dir, file)
            self.run_migration(file_path)

    def rollback(self, migration_file):
        """Rollback a migration"""
        # Note: Oracle implicitly auto-commits DDL statements (CREATE, DROP, ALTER).
        # To rollback structural changes in Oracle, you must execute a 'down' script 
        # (e.g., DROP TABLE) rather than relying on a database transaction rollback.
        
        filename = os.path.basename(migration_file)
        print(f"Attempting rollback for: {filename}")
        
        with open(migration_file, 'r') as f:
            sql_script = f.read()
            
        statements = [s.strip() for s in sql_script.split(';') if s.strip()]
        
        try:
            for statement in statements:
                self.cursor.execute(statement)
                
            self.cursor.execute(
                "DELETE FROM migration_history WHERE migration_name = :name",
                [filename.replace('_down.sql', '.sql')] 
            )
            self.db.commit()
            print(f"Successfully rolled back {filename}")
            
        except oracledb.Error as e:
            self.db.rollback()
            print(f"Rollback failed for {filename}: {e}")
            raise